apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
