apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: {{ .Values.resultServer.replicaCount }}
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
        - image: "{{ .Values.resultServer.image.repository }}:{{ .Values.resultServer.image.tag }}"
          imagePullPolicy: {{ .Values.resultServer.image.pullPolicy }}
          name: resultserver
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              # value: Devenes_1
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_admin_password
          envFrom:
            - configMapRef:
                name: server-config
          resources:
            {{- toYaml .Values.resultServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.resultServer.probes.path }}
              port: 80
            initialDelaySeconds: {{ .Values.resultServer.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.resultServer.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.resultServer.probes.path }}
              port: 80
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.resultServer.probes.periodSeconds }}

