apiVersion: v1
kind: Service
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-svc
spec:
  ports:
    - port: {{ .Values.resultServer.service.port }}
      protocol: TCP
      targetPort: 80
      nodePort: {{ .Values.resultServer.service.nodePort }}
  selector:
    app: resultserver-deploy
  type: {{ .Values.resultServer.service.type }}
