apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-deploy
  name: webserver-svc
spec:
  ports:
    - port: {{ .Values.webServer.service.port }}
      protocol: TCP
      targetPort: 80
      nodePort: {{ .Values.webServer.service.nodePort }}
  selector:
    app: webserver-deploy
  type: {{ .Values.webServer.service.type }}
