apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: {{ .Values.webServer.replicaCount }}
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
        - image: "{{ .Values.webServer.image.repository }}:{{ .Values.webServer.image.tag }}"
          imagePullPolicy: {{ .Values.webServer.image.pullPolicy }}
          name: webserver
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              # value: Devenes_1
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_admin_password
          envFrom:
            - configMapRef:
                name: server-config
          resources:
            {{- toYaml .Values.webServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.webServer.probes.path }}
              port: 80
            initialDelaySeconds: {{ .Values.webServer.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.webServer.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webServer.probes.path }}
              port: 80
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.webServer.probes.periodSeconds }}

